
''' 
TEST CASES:

1 Resource submission basic: only url and resource rating
INPUT
- url: https://www.google.com/
- resource rating: 1


2 Resource submission basic: invalid url and resource rating
INPUT
- url: this_is_an_invalid_url
- resource usefulness rating: 2


3 Resource submission basic: not found url and resource rating
INPUT
- url: http://127.0.0.1:8000/notfoundurl
- resource usefulness rating: 3


4 Resource submission with tag and comment: url, resource rating, tag, comment
INPUT
- url: https://www.ualberta.ca/
- resource usefulness rating: 4
- tags: university, alberta, test (will need to add these tags to database before searching)
- comments: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa strong. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede link mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.


5 Resource submission with tag, comment and attachment: url, resource rating, tag, comment, attachement
INPUT
- url: https://reactjs.org/
- resource usefulness rating: 5
- tags: react, web development, test (will need to add these tags to database before searching)
- comments: React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.

'''

# Generated by Selenium IDE
from django.test import LiveServerTestCase
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium import webdriver
import json
import time
import sys
from ..models import Resource
sys.path.append('...')
from authentication.models import CustomUser

import time 


class TestResourceSubmission(LiveServerTestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        super(TestResourceSubmission, self).setUp()

    def tearDown(self):
        self.driver.quit()
        super(TestResourceSubmission, self).tearDown()

    def setup_test_db(self):
        self.user_email = "test@gmail.com"
        self.user_password = "test"
        user = CustomUser.objects.create_user(
            email=self.user_email,
            password=self.user_password
        )
        user.save()
        Resource.objects.all().delete()

    def test_resource_submission(self):
        self.setup_test_db()
        header = "Google"
        url = "https://www.google.com/"

        self.driver.implicitly_wait(10)

        self.driver.get("http://127.0.0.1:8000/chatbotportal/app")
        self.driver.set_window_size(1186, 764)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.NAME, "email").send_keys(self.user_email)
        self.driver.find_element(By.NAME, "password").send_keys(self.user_password)
        self.driver.find_element(By.NAME, "login_button").click()
        self.driver.find_element(By.LINK_TEXT, "My Resources").click()
        self.driver.find_element(By.CSS_SELECTOR, "body")        
        self.driver.find_element(By.NAME, "submit_a_resource").click()
        self.driver.find_element(By.NAME, "url").send_keys(url)
        self.driver.find_element(By.XPATH, ("//i[2]")).click()
        self.driver.find_element(By.NAME, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "My Resources").click()
        self.driver.find_element(By.XPATH, ("//a/div/div")).click()
        test_header = self.driver.find_element(By.XPATH, ("//h3")).text
        test_url = self.driver.find_element(By.CSS_SELECTOR, ".Resource__link____1ER80").text
        self.driver.find_element(By.CSS_SELECTOR, ".Resource__link____1ER80").click()

        assert header == test_header
        assert url == test_url
