language: python
python:
  - "3.7"
services:
  - mysql
env: 
  -DJANGO=2.2.5 DB=mysql
install:
  - pip install -r requirements.txt
script:
  - python ./ChatbotPortal/manage.py test resource.tests
  - python ./ChatbotPortal/manage.py test authentication.tests


