language: python
python:
  - "3.7"
services:
  - mysql
env: 
  -DJANGO=2.2.5 DB=mysql
install:
  - pip install -r requirements.txt
before-script:
- mysql -e 'drop database if exists test; create database test;' -u root
script:
  - rm ./ChatbotPortal/db.sqlite3
  - find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
  - find . -path "*/migrations/*.pyc"  -delete
  - python ./ChatbotPortal/manage.py makemigrations
  - python ./ChatbotPortal/manage.py migrate
  - python ./ChatbotPortal/manage.py migrate --run-syncdb




