language: python
python:
  - "3.7"
services:
  - mysql
env: 
  -DJANGO=2.2.5 DB=mysql
install:
  - pip install -r requirements.txt
before-script:
- mysql -e 'drop database if exists test; create database test;' -u root
script:
  - python ./ChatbotPortal/manage.py makemigrations



