language: python
python:
  - "3.7"
#services:
#  - mysql
install:
  - pip install -r requirements.txt
before-script:
- mysql -e 'drop database if exists test; create database test;' -u root
script:
  - rm ./ChatbotPortal/db.sqlite3
  - python manage.py migrate --fake admin zero
  - find . -path "*/migrations/*.py" -delete
  - find . -path "*/migrations/*.pyc"  -delete
  - python ./ChatbotPortal/manage.py makemigrations
  - python manage.py migrate --fake-initial
#  - python ./ChatbotPortal/manage.py migrate
#  - python ./ChatbotPortal/manage.py migrate --run-syncdb




