# Generated by Django 2.2.6 on 2020-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191124_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
