# Generated by Django 2.2.6 on 2021-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
