# Generated by Django 3.2 on 2021-09-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviews_final_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='resource_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
