# Generated by Django 3.2 on 2021-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviews_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='question_answers',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
