# Generated by Django 2.2.6 on 2019-11-18 05:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resource.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='resource_attachment/', validators=[resource.validators.validate_file_size])),
                ('created_by_user', models.CharField(default='Unknown user', max_length=100)),
                ('created_by_user_pk', models.IntegerField(default=-1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('review_status', models.CharField(default='pending', max_length=50)),
                ('website_summary_metadata', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Category')),
                ('tags', models.ManyToManyField(blank=True, to='resource.Tag')),
            ],
        ),
    ]
