# Generated by Django 2.2.6 on 2019-11-17 22:41

from django.db import migrations

def initialize_categories(apps, schema_editor):
    Category = apps.get_model('resource', 'Category')
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).bulk_create([
        Category(name="document/PDF"),
        Category(name="email"),
        Category(name="phone number"),
        Category(name="physical address"),
        Category(name="picture/graphic"),
        Category(name="Text (definition/statistic)"),
        Category(name="video"),
        Category(name="website"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_category_resource_tag'),
    ]

    operations = [
        migrations.RunPython(initialize_categories),
    ]
