# Generated by Django 2.2.6 on 2019-11-18 07:38

from django.db import migrations

def initialize_tags(apps, schema_editor):
    Tag = apps.get_model('resource', 'Tag')
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).bulk_create([
        Tag(id=1, name='English', approved=True),
        Tag(id=2, name='French', approved=True),
        Tag(id=3, name='Parent', approved=True),
        Tag(id=4, name='Male', approved=True),
        Tag(id=5, name='Female', approved=True),
        Tag(id=6, name='Diagnosis', approved=True),
        Tag(id=7, name='Age 1-2', approved=True),
        Tag(id=8, name='Age 3-5', approved=True),
        Tag(id=9, name='Age 6-11', approved=True),
        Tag(id=10, name='Age 12-17', approved=True),
        Tag(id=11, name='Autism', approved=True),
        Tag(id=12, name='ADHD', approved=True),
        Tag(id=13, name='Intellectual disability', approved=True),
        Tag(id=14, name='Manage challenging behaviors', approved=True),
        Tag(id=15, name='Resource challenging behaviors', approved=True),
        Tag(id=16, name='Manage emotions', approved=True),
        Tag(id=17, name='Age / development / chronological / corrected age /developmental level', approved=True),
        Tag(id=18, name='Social Skills : Age 1-2', approved=True),
        Tag(id=19, name='Gross Motor: Age 1-2', approved=True),
        Tag(id=20, name='Language Skills: Age 1-2, receptive language', approved=True),
        Tag(id=21, name='Fine Motor Skills: Age 1-2', approved=True),
        Tag(id=22, name='Social Skills: Age 3-5', approved=True),
        Tag(id=23, name='Gross Motor: Age 3-5', approved=True),
        Tag(id=24, name='Language Skills: Age 3-5', approved=True),
        Tag(id=25, name='Fine Motor Skills: Age 3-5', approved=True),
        Tag(id=26, name='Social Skills: Age 6-11', approved=True),
        Tag(id=27, name='Gross Motor Skills: Age 6-11', approved=True),
        Tag(id=28, name='Language Skills: Age 6-11', approved=True),
        Tag(id=29, name='Fine Motor Skills: Age 6-11', approved=True),
        Tag(id=30, name='Social Skills: Age 12-17', approved=True),
        Tag(id=31, name='Gross Motor Skills: Age 12-17', approved=True),
        Tag(id=32, name='Language Skills: Age 12-17', approved=True),
        Tag(id=33, name='Fine Motor Skills: Age 12-17', approved=True),
        Tag(id=34, name='Behaviour problem ', approved=True),
        Tag(id=35, name='Diagnosis, developmental', approved=True),
        Tag(id=36, name='Skills deficit', approved=True),
        Tag(id=37, name='Services deficit', approved=True),
        Tag(id=38, name='Summary', approved=True),
        Tag(id=39, name='Challenging Behaviour', approved=True),
        Tag(id=40, name='Challenging Behaviour Trigger', approved=True),
        Tag(id=41, name='Environment Deficit', approved=True),
        Tag(id=42, name='Regular Activities deficit', approved=True),
        Tag(id=43, name='Children', approved=True),
        Tag(id=44, name='Time management', approved=True),
        Tag(id=45, name='Energy', approved=True),
        Tag(id=46, name='Stress', approved=True),
        Tag(id=47, name='Sleep', approved=True),
        Tag(id=48, name='Emotion', approved=True),
        Tag(id=49, name='Partnership', approved=True),
        Tag(id=50, name='Sexual / Gender Identity', approved=True),
        Tag(id=51, name='Sexual Identity', approved=True),
        Tag(id=52, name='Gender Identity', approved=True),
        Tag(id=53, name='Environment-immigration', approved=True),
        Tag(id=54, name='Environment - social / physical', approved=True),
        Tag(id=55, name='Environment-rent', approved=True),
        Tag(id=56, name='Occupation', approved=True),
        Tag(id=57, name='Attention deficit hyperactivity disorder', approved=True),
        Tag(id=58, name='learning disability', approved=True),
        Tag(id=59, name='Funding', approved=True),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_initial_categories'),
    ]

    operations = [
        migrations.RunPython(initialize_tags),
    ]
