# Generated by Django 2.2.6 on 2019-11-24 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_initial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created_by_user',
            field=models.CharField(blank=True, default='Unknown user', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_by_user_pk',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='review_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='website_summary_metadata',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
