# Generated by Django 2.2.6 on 2019-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20191123_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='public_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
