# Generated by Django 2.2.6 on 2019-11-29 02:11

from django.db import migrations

def initialize_resources(apps, schema_editor):
    Resource = apps.get_model('resource', 'Resource')
    Tag = apps.get_model('resource', 'Tag')
    Category = apps.get_model('resource', 'Category')
    db_alias = schema_editor.connection.alias

    website_category = Category.objects.get(id=1)

    Resource.objects.using(db_alias).bulk_create([
        Resource(id=1, url="http://www.chadd.org/Understanding-ADHD/For-Parents-Caregivers.aspx", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=2, url="http://www.chadd.org/Understanding-ADHD/For-Parents-Caregivers/Treatment-Overview/Psychosocial-Treatments.aspx", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=3, url="https://cdpp.ca/community-partner/active-living-alliance-canadians-disability", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=4, url="http://www.henryspink.org/adhd.htm", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=5, url="http://jooay.com", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=6, url="https://www.albertahealthservices.ca/info/service.aspx?id=5770", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=7, url="https://myhealth.alberta.ca/Alberta/Pages/self-harm-and-youth.aspx", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=8, url="https://www.nspcc.org.uk/preventing-abuse/keeping-children-safe/self-harm/", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=9, url="https://www.autismspeaks.org/family-services/tool-kits/challenging-behaviors-tool-kit", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=10, url="http://www.cerebra.org.uk/research/research-papers/self-injurious-behaviour-in-children-with-intellectual-disability/", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=11, url="http://parentinfo.org/article/self-injury-and-children-with-intellectual-disabilities-what-parents-should-know", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=12, url="https://iancommunity.org/aic/challenging-behavior-autism-self-injury", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=13, url="https://iancommunity.org/challenging-behaviors", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=14, url="https://www.autism.com/symptoms_self-injury", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=15, url="https://myhealth.alberta.ca/health/pages/conditions.aspx?Hwid=tv6556", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=16, url="https://myhealth.alberta.ca/Health/pages/conditions.aspx?hwid=abp2631", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=17, url="https://www.cdc.gov/ncbddd/disabilityandsafety/aggression.html", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=18, url="https://raisingchildren.net.au/autism/behaviour/common-concerns/aggressive-behaviour-asd", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=19, url="https://www.autismspeaks.org/family-services/tool-kits/challenging-behaviors-tool-kit", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=20, url="https://iancommunity.org/tags/aggression-and-autism", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=21, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/canada-caregiver-amount.html", title="Canada Caregiver Credit (CCC)", website_summary_metadata="The Canada Caregiver Credit is a non-refundable tax credit for individuals who are caring for a dependent with an impairment of physical or cognitive functions.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=22, url="https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview.html", title="Canada Child Benefit (CCB)", website_summary_metadata="The Canada Child Benefit is a tax-free monthly payment made to eligible families to help them with the cost of raising children under 18 years of age.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=23, url="https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html", title="Child Disability Benefit", website_summary_metadata="The Child Disability Benefit is a tax-free monthly payment to help eligible families with the cost of raising children under 18 years of age. To be eligible, families must already be registered for the Disability Tax Credit", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=24, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-214-child-care-expenses.html", title="Child Care Expenses Deduction", website_summary_metadata="The Child Care Expenses Deduction provides relief to individuals who incur child care expenses in order to work, carry on a business or undertake certain education activities.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=25, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit.html", title="Disability Tax Credit (DTC)", website_summary_metadata="The disability tax credit is a non-refundable tax credit that helps persons with disabilities or their supporting persons reduce the amount of income tax they may have to pay.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=26, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-318-disability-amount-transferred-a-dependant.html", title="Disability Amount Transfer from a Dependent", website_summary_metadata="The Disability Amount Transfer allows dependent children to transfer the Disability Tax Credit to a caregiver.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=27, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/lines-330-331-eligible-medical-expenses-you-claim-on-your-tax-return.html", title="Medical Expenses Tax Credit", website_summary_metadata="The Medical Expenses Tax Credit allows individuals to claim eligible medical expenses for themselves or for their dependent child/children on an income tax and benefit return.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=28, url="https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/registered-disability-savings-plan-rdsp.html", title="Registered Disability Savings Plan (RDSP)", website_summary_metadata="The Registered Disability Savings Plan is a savings plan for long-term financial stability specific to persons with disabilities, where the government matches contributions.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=29, url="https://www.alberta.ca/aish.aspx", title="Assured Income for the Severely Handicapped (AISH)", website_summary_metadata="The Assured Income for Severely Handicapped program provides financial and health benefits to eligible Albertans with a permanent medical condition, such as a developmental disability, that prevents them from earning a living.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=30, url="https://www.alberta.ca/disability-related-employment-supports.aspx", title="Disability-Related Employment Support (DRES)", website_summary_metadata="Disability Related Employment Supports help Albertans overcome disabilityrelated barriers to their education, career and employment goals. This program provides job-search supports, workplace supports and educational supports.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=31, url="https://www.alberta.ca/persons-with-developmental-disabilities-pdd.aspx", title="Persons with Developmental Disabilities (PDD)", website_summary_metadata="Persons with Developmental Disabilities funds programs and services to help Albertans with developmental disabilities to be a part of their communities and live as independently as they can. The program funds Community Living Supports, Employment Supports, Community Access Supports, and Specialized Community Supports.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=32, url="https://www.alberta.ca/child-care-subsidy.aspx", title="Alberta Child Care Subsidy", website_summary_metadata="The Alberta Child Care Subsidy Program helps eligible families pay child care costs for children (0-12 years of age) enrolled in an approved family day home, a licensed daycare program, a licensed out-of-school care program, or a licensed group family child care program", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=33, url="https://www.alberta.ca/alberta-child-health-benefit.aspx", title="Alberta Child Health Benefit", website_summary_metadata="The Alberta Child Health Benefit covers children’s health expenses for families with low incomes.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=34, url="https://www.alberta.ca/alberta-family-employment-tax-credit.aspx", title="Alberta Family Employment Tax Credit (AFETC) ", website_summary_metadata="The Alberta Family Employment Tax Credit helps lower and middle-income working families provide for their children.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=35, url="https://www.alberta.ca/fscd.aspx", title="Family Support for Children with Disabilities (FSCD)", website_summary_metadata="The Family Support for Children with Disabilities program provides a wide range of family-centered supports and services. Services are meant to help strengthen a families’ ability to promote their child’s healthy development, and encourage their child’s participation in activities at home and in the community.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=36, url="https://www.alberta.ca/alberta-aids-to-daily-living.aspx", title="Alberta Aids to Daily Living (AADL)", website_summary_metadata="The Alberta Aids to Daily Living program assists Albertans with a long-term disability, chronic illness, or terminal illness in maintaining independence in their community", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=37, url="https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/care-options-and-cost/choice-in-supports-for-independent-living", title="Choice in Supports for Independent Living (CSIL)", website_summary_metadata="Choice in Supports for Independent Living is a self-directed option for eligible home support clients. Participants receive funds directly from their local health authority to purchase their own home support services.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=38, url="https://www.communitylivingbc.ca/", title="Community Living BC", website_summary_metadata="Community Living BC funds a range of supports and services to adults with developmental disabilities.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=39, url="https://www2.gov.bc.ca/gov/content/family-social-supports/services-for-people-with-disabilities/disability-assistance", title="Disability Assistance", website_summary_metadata="Disability Assistance provides financial and/or health support to low income persons with disabilities.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=40, url="https://www.communitylivingbc.ca/what-support-is-available/preparing-access-clbc-supports/services-to-adults-with-developmental-disabilities-stadd/", title="Services to Adults with Developmental Disabilities (STADD)", website_summary_metadata="Services to Adults with Developmental Disabilities supports individuals transitioning into adulthood (age 16-24) through services provided by Navigators. Navigators work with transitioning individuals to ensure that they are able to access services that support their individual needs, and to help coordinate transition planning.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=41, url="https://www2.gov.bc.ca/gov/content/family-social-supports/caring-for-young-children/child-care-funding/child-care-benefit", title="Affordable Child Care Benefit (Formerly Child Care Subsidy)", website_summary_metadata="The Affordable Child Care Benefit helps families to reduce the cost of child care each month.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=42, url="https://www2.gov.bc.ca/gov/content/health/managing-your-health/healthy-women-children/child-behaviour-development/special-needs/complex-health-needs/at-home-program", title="At Home Program (AHP)", website_summary_metadata="The At Home Program is intended to assist parents or guardians with some of the extraordinary costs of caring for a child with severe disabilities at home.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=43, url="https://www2.gov.bc.ca/gov/content/health/managing-your-health/healthy-women-children/child-behaviour-development/special-needs/autism-spectrum-disorder/autism-funding", title="Autism Funding Program", website_summary_metadata="The Autism Funding Program funds eligible service providers that support the needs of children with disabilities and their families.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=44, url="https://www2.gov.bc.ca/gov/content/health/managing-your-health/healthy-women-children/child-behaviour-development/special-needs/fetal-alcohol-spectrum-disorder-fasd", title="FASD Key Worker and Support Program", website_summary_metadata="The FASD Key Worker and Support Program provides social and educational support to families of children and youth under 19 years of age with Fetal Alcohol Spectrum Disorder (FASD) and similar neurodevelopmental conditions. Support is provided through Key Workers, which are assigned to families enrolled in this program", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=45, url="https://www.at-bc.ca/", title="Assistive Technology BC (ATBC)", website_summary_metadata="Assistive Technology BC provides assistive technology resources to make learning and working environments accessible for people with disabilities", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=46, url="https://www.gov.mb.ca/fs/clds/index.html", title="Community Living disABILITY Services (CLDS)", website_summary_metadata="Community Living disABILITY Services offer a range of day and residential services aimed at providing adults with disabilities the opportunity for independence in a community setting.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=47, url="https://www.gov.mb.ca/fs/eia/eia_disability.html", title="Income Assistance for Persons with Disabilities", website_summary_metadata="Income Assistance for Persons with Disabilities provides financial support to low income persons with disabilities.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=48, url="https://www.gov.mb.ca/wd/ites/vrmanual/index.html", title="marketABILITIES (now called Employability Assistance for People with Disabilities)", website_summary_metadata="The marketABILITIES program provides employment-focused services to assist adults with disabilities in preparing for, obtaining, and maintaining employment.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
        Resource(id=49, url="https://www.gov.mb.ca/fs/cds/index.html", title="Children’s disABILITY Services", website_summary_metadata="Children’s disABILITY Services support families who are raising a child (or children) with developmental and physical disabilities to meet some of the additional needs they may have.", review_status="approved", created_by_user="Admin", rating=5, category=website_category),
    ])

    children_tag = Tag.objects.get(id=43)
    adult_tag = Tag.objects.get(id=60)
    funding_tag = Tag.objects.get(id=59)

    funding_resources = Resource.objects.filter(id__in=range(21, 29))
    child_resources = Resource.objects.filter(id__in=[32,33,34,35,41,42,43,44,49])
    adult_resources = Resource.objects.filter(id__in=[29,30,31,37,38,39,40,46,47,48])
    child_adult_resources = Resource.objects.filter(id__in=[36,45])

    for resource in list(funding_resources):
        resource.tags.add(funding_tag)
        resource.save()

    for resource in list(child_resources):
        resource.tags.add(funding_tag)
        resource.tags.add(children_tag)
        resource.save()

    for resource in list(adult_resources):
        resource.tags.add(funding_tag)
        resource.tags.add(adult_tag)
        resource.save()

    for resource in list(child_adult_resources):
        resource.tags.add(funding_tag)
        resource.tags.add(children_tag)
        resource.tags.add(adult_tag)
        resource.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_resource_public_view_count'),
    ]

    operations = [
        migrations.RunPython(initialize_resources),
    ]
