# Generated by Django 2.2.6 on 2020-07-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_initial_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='review_comments',
            field=models.TextField(blank=True, default='No Comment', null=True),
        ),
    ]
