# Generated by Django 2.2.6 on 2020-07-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20200701_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
