# Generated by Django 2.2.6 on 2021-07-07 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_tag_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='chatbot_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='distress_level_max',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='resource',
            name='distress_level_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='phone_numbers',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999', one per line. Up to 15 digits allowed per number.", regex='^(\\d{10,15}\\;)*$')]),
        ),
        migrations.AddField(
            model_name='resource',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('SR', 'Program/Service'), ('RS', 'Educational/Informational'), ('BT', 'Service/Resource')], default='RS', max_length=2),
        ),
        migrations.AddField(
            model_name='resource',
            name='text_numbers',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message="Text number must be entered in the format: '9999', one per line. Up to 15 digits allowed per number.", regex='^(\\d{3,15}\\;)*$')]),
        ),
    ]
