# Generated by Django 2.2.6 on 2021-07-08 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0012_auto_20210708_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone_numbers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999', one per line. Up to 15 digits allowed per number.", regex='^(\\d{10,15}\\;)*$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text_numbers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Text number must be entered in the format: '9999', one per line. Up to 15 digits allowed per number.", regex='^(\\d{3,15}\\;)*$')]),
        ),
    ]
