# Generated by Django 2.2.6 on 2021-07-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_auto_20210708_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
