# Generated by Django 2.2.6 on 2021-07-27 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_resource_physical_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='phone_numbers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1234567890; , one per line. Up to 15 digits allowed per number.', regex='^(\\d{10,15}\\;)*$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text_numbers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Text number must be entered in the format: 1234567890; , one per line. Up to 15 digits allowed per number.', regex='^(\\w{3,15}\\;)*$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
