# Generated by Django 2.2.6 on 2021-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0016_auto_20210727_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hours_of_operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
