# Generated by Django 2.2.6 on 2021-08-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_resource_hours_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_reviewer',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='assigned_reviewer_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_status_2',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
