# Generated by Django 3.2 on 2021-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_auto_20210801_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='organization_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
