# Generated by Django 3.2 on 2021-08-11 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_resource_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_free',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
