# Generated by Django 3.2 on 2021-08-11 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0020_resource_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='informational_resource_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='physical_address',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Address format is not correct.', regex='^((.)+\\,)*((.{1,100}))$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text_numbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
