# Generated by Django 3.2 on 2021-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0021_auto_20210811_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
