# Generated by Django 3.2 on 2021-08-16 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0022_resource_resource_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='require_membership',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone_numbers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 1234567890; , one per line. Up to 15 digits allowed per number.', regex='^(\\d{3,15}\\;)*$')]),
        ),
    ]
