# Generated by Django 3.2 on 2021-09-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0024_auto_20210816_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='distress_level_max',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='distress_level_min',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='require_membership',
        ),
    ]
