# Generated by Django 3.2 on 2021-09-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0025_auto_20210909_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
