# Generated by Django 3.2 on 2021-09-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_remove_resource_chatbot_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='organization_description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_format',
        ),
    ]
