# Generated by Django 3.2 on 2021-09-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0030_rename_definition_resource_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='informational_resource_text',
            new_name='definition',
        ),
    ]
