# Generated by Django 3.2 on 2021-11-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0033_auto_20210929_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='references',
            new_name='index',
        ),
        migrations.AlterField(
            model_name='resource',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
