# Generated by Django 3.2 on 2021-11-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0034_auto_20211115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
