# Generated by Django 3.2 on 2022-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0036_auto_20211123_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='chatbot_api_rcmnd_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='portal_search_rcmnd_count',
            field=models.IntegerField(default=0),
        ),
    ]
