# Generated by Django 3.0.7 on 2022-02-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0036_auto_20211123_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_reviewer_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_status_3',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
