# Generated by Django 3.2 on 2022-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0037_auto_20220210_2335'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='resource_ta_name_5f083b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['approved'], name='resource_ta_approve_ccf247_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_category'], name='resource_ta_tag_cat_676f30_idx'),
        ),
    ]
