# Generated by Django 3.2 on 2022-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0038_auto_20220211_1020'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['review_status'], name='resource_re_review__0bf177_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['review_status_2'], name='resource_re_review__b4067a_idx'),
        ),
    ]
