# Generated by Django 3.2 on 2022-02-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0037_auto_20220210_1703'),
        ('resource', '0039_auto_20220211_1023'),
    ]

    operations = [
    ]
