# Generated by Django 3.2 on 2022-05-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0040_merge_0037_auto_20220210_1703_0039_auto_20220211_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='chatbot_frontend_click_count',
            field=models.IntegerField(default=0),
        ),
    ]
