# Generated by Django 3.2 on 2022-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0041_resource_chatbot_frontend_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='chatbot_frontend_click_more_count',
            field=models.IntegerField(default=0),
        ),
    ]
