# Generated by Django 3.2 on 2022-07-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0043_auto_20220613_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='organization_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
