# Generated by Django 3.2 on 2024-08-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0044_tagrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_reviewer_1_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='assigned_reviewer_2_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_status_1_1',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_status_2_2',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_1_1_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_1_1_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_2_2_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_2_2_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_2_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_2_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewer_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.tag')),
            ],
        ),
    ]
